
<field:director itemname="导演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="10" page="">
</field:director>

<field:actor itemname="主演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="64" page="">
</field:actor>

<field:year itemname="年代" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="2012,2013,2014,2015,2016"  maxlength="250" page="">
</field:year>

<field:area itemname="地区" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="大陆,港台,日韩,欧美,其他"  maxlength="250" page="">
</field:area>
