<div class="movie_tui">
						<div class="movie_tui_pic"><a href="#" target="_blank"><img alt="山楂树之恋" src="[field:litpic/]" /></a></div>
						<h4><a href="#" target="_blank">史上最纯的爱情片：《[field:title/]》</a></h4>
						<span>导演：<a href="#" target="_blank">[field:director/]</a>主演：<a href="#" target="_blank">[field:actor/]</a>年代：<a href="#" target="_blank">[field:year]</a></span>
						<p>[field:content/]</p>
					</div>